---
data:
  train:
    batch_size: [32, 64, 128, 256]
  val:
    batch_size: [32, 64, 128, 256]
  test:
    batch_size: [32, 64, 128, 256]

model:
  hidden_channles: [16, 32, 64, 128, 256, 512]
  num_layers: [2, 3, 4, 5, 6, 7, 8, 9, 10]
  lr:
    low: 0.0001
    high: 0.1
  dropout:
    low: 0.0
    high: 0.5
